export type Emoji = {
  e: string; // emoji character
  k: string[]; // keywords
};

export type EmojiCategory = {
  name: string;
  emojis: Emoji[];
};

export const emojiCategories: EmojiCategory[] = [
  {
    name: 'Smileys & Emotion',
    emojis: [
      { e: '😀', k: ['grinning', 'face', 'smile', 'happy'] },
      { e: '😃', k: ['grinning', 'face', 'big', 'eyes', 'smile', 'happy'] },
      { e: '😄', k: ['grinning', 'face', 'smiling', 'eyes', 'smile', 'happy'] },
      { e: '😁', k: ['beaming', 'face', 'smiling', 'eyes', 'smile', 'happy'] },
      { e: '😆', k: ['grinning', 'squinting', 'face', 'laugh', 'happy'] },
      { e: '😅', k: ['grinning', 'face', 'sweat', 'happy', 'nervous'] },
      { e: '🤣', k: ['rolling', 'on', 'floor', 'laughing', 'rofl', 'lol'] },
      { e: '😂', k: ['face', 'tears', 'joy', 'laugh'] },
      { e: '🙂', k: ['slightly', 'smiling', 'face'] },
      { e: '🙃', k: ['upside-down', 'face', 'sarcasm'] },
      { e: '😉', k: ['winking', 'face', 'wink'] },
      { e: '😊', k: ['smiling', 'face', 'eyes', 'blush', 'happy'] },
      { e: '😇', k: ['smiling', 'face', 'halo', 'angel', 'innocent'] },
      { e: '🥰', k: ['smiling', 'face', 'hearts', 'love', 'crush'] },
      { e: '😍', k: ['smiling', 'face', 'heart-eyes', 'love', 'crush'] },
      { e: '🤩', k: ['star-struck', 'excited', 'eyes'] },
      { e: '😘', k: ['face', 'blowing', 'kiss'] },
      { e: '😗', k: ['kissing', 'face'] },
      { e: '😚', k: ['kissing', 'face', 'closed', 'eyes'] },
      { e: '😙', k: ['kissing', 'face', 'smiling', 'eyes'] },
      { e: '😋', k: ['face', 'savoring', 'food', 'yum'] },
      { e: '😛', k: ['face', 'with', 'tongue', 'silly'] },
      { e: '😜', k: ['winking', 'face', 'tongue', 'silly'] },
      { e: '🤪', k: ['zany', 'face', 'silly', 'crazy'] },
      { e: '😝', k: ['squinting', 'face', 'tongue', 'silly'] },
      { e: '🤗', k: ['hugging', 'face', 'hug'] },
      { e: '🤔', k: ['thinking', 'face', 'think'] },
      { e: '🤫', k: ['shushing', 'face', 'shh', 'quiet'] },
      { e: '🤭', k: ['face', 'with', 'hand', 'over', 'mouth', 'oops', 'gasp'] },
      { e: '🤨', k: ['face', 'with', 'raised', 'eyebrow', 'suspicious', 'skeptical'] },
      { e: '😐', k: ['neutral', 'face', 'meh'] },
      { e: '😑', k: ['expressionless', 'face'] },
      { e: '😶', k: ['face', 'without', 'mouth', 'speechless'] },
      { e: '😏', k: ['smirking', 'face', 'smug', 'smirk'] },
      { e: '😒', k: ['unamused', 'face', 'annoyed'] },
      { e: '🙄', k: ['face', 'with', 'rolling', 'eyes', 'annoyed'] },
      { e: '😬', k: ['grimacing', 'face', 'awkward', 'nervous'] },
      { e: '🤥', k: ['lying', 'face', 'liar', 'pinocchio'] },
      { e: '😌', k: ['relieved', 'face', 'relief'] },
      { e: '😔', k: ['pensive', 'face', 'sad'] },
      { e: '😪', k: ['sleepy', 'face', 'tired'] },
      { e: '🤤', k: ['drooling', 'face'] },
      { e: '😴', k: ['sleeping', 'face', 'zzz'] },
      { e: '😷', k: ['face', 'with', 'medical', 'mask', 'sick'] },
      { e: '🤒', k: ['face', 'with', 'thermometer', 'sick', 'fever'] },
      { e: '🤕', k: ['face', 'with', 'head-bandage', 'injured'] },
      { e: '🤢', k: ['nauseated', 'face', 'sick'] },
      { e: '🤮', k: ['face', 'vomiting', 'sick'] },
      { e: '🤧', k: ['sneezing', 'face', 'sick', 'sneeze'] },
      { e: '🥵', k: ['hot', 'face', 'sweating'] },
      { e: '🥶', k: ['cold', 'face', 'freezing'] },
      { e: '🥴', k: ['woozy', 'face', 'drunk'] },
      { e: '😵', k: ['dizzy', 'face'] },
      { e: '🤯', k: ['exploding', 'head', 'mind', 'blown'] },
      { e: '🤠', k: ['cowboy', 'hat', 'face'] },
      { e: '🥳', k: ['partying', 'face', 'party'] },
      { e: '😎', k: ['smiling', 'face', 'sunglasses', 'cool'] },
      { e: '🤓', k: ['nerd', 'face'] },
      { e: '🧐', k: ['face', 'with', 'monocle'] },
      { e: '😕', k: ['confused', 'face'] },
      { e: '😟', k: ['worried', 'face'] },
      { e: '🙁', k: ['slightly', 'frowning', 'face'] },
      { e: '😮', k: ['face', 'with', 'open', 'mouth', 'surprised'] },
      { e: '😯', k: ['hushed', 'face'] },
      { e: '😲', k: ['astonished', 'face'] },
      { e: '😳', k: ['flushed', 'face', 'embarrassed'] },
      { e: '🥺', k: ['pleading', 'face', 'puppy', 'eyes'] },
      { e: '😦', k: ['frowning', 'face', 'open', 'mouth'] },
      { e: '😧', k: ['anguished', 'face'] },
      { e: '😨', k: ['fearful', 'face'] },
      { e: '😰', k: ['anxious', 'face', 'sweat'] },
      { e: '😥', k: ['sad', 'but', 'relieved', 'face'] },
      { e: '😢', k: ['crying', 'face', 'sad'] },
      { e: '😭', k: ['loudly', 'crying', 'face', 'sad', 'sob'] },
      { e: '😱', k: ['face', 'screaming', 'in', 'fear', 'scream'] },
      { e: '😖', k: ['confounded', 'face'] },
      { e: '😣', k: ['persevering', 'face'] },
      { e: '😞', k: ['disappointed', 'face', 'sad'] },
      { e: '😓', k: ['downcast', 'face', 'sweat'] },
      { e: '😩', k: ['weary', 'face'] },
      { e: '😫', k: ['tired', 'face'] },
      { e: '😤', k: ['face', 'with', 'steam', 'from', 'nose', 'angry'] },
      { e: '😠', k: ['angry', 'face'] },
      { e: '😡', k: ['pouting', 'face', 'angry', 'mad'] },
      { e: '🤬', k: ['face', 'with', 'symbols', 'on', 'mouth', 'swearing'] },
      { e: '😈', k: ['smiling', 'face', 'with', 'horns', 'devil'] },
      { e: '👿', k: ['angry', 'face', 'with', 'horns', 'devil'] },
      { e: '💀', k: ['skull', 'dead'] },
      { e: '☠️', k: ['skull', 'and', 'crossbones', 'danger', 'dead'] },
      { e: '🤡', k: ['clown', 'face'] },
      { e: '👹', k: ['ogre'] },
      { e: '👺', k: ['goblin'] },
      { e: '👻', k: ['ghost', 'halloween'] },
      { e: '👽', k: ['alien'] },
      { e: '👾', k: ['alien', 'monster', 'game'] },
      { e: '🤖', k: ['robot'] },
      { e: '😺', k: ['grinning', 'cat'] },
      { e: '😸', k: ['grinning', 'cat', 'smiling', 'eyes'] },
      { e: '😹', k: ['cat', 'tears', 'joy'] },
      { e: '😻', k: ['smiling', 'cat', 'heart-eyes'] },
      { e: '😼', k: ['cat', 'wry', 'smile'] },
      { e: '😽', k: ['kissing', 'cat'] },
      { e: '🙀', k: ['weary', 'cat'] },
      { e: '😿', k: ['crying', 'cat'] },
      { e: '😾', k: ['pouting', 'cat'] },
      { e: '🙈', k: ['see-no-evil', 'monkey'] },
      { e: '🙉', k: ['hear-no-evil', 'monkey'] },
      { e: '🙊', k: ['speak-no-evil', 'monkey'] },
    ],
  },
  {
    name: 'Hearts & Symbols',
    emojis: [
      { e: '💋', k: ['kiss', 'mark'] },
      { e: '💌', k: ['love', 'letter'] },
      { e: '❤️', k: ['red', 'heart', 'love'] },
      { e: '🧡', k: ['orange', 'heart'] },
      { e: '💛', k: ['yellow', 'heart'] },
      { e: '💚', k: ['green', 'heart'] },
      { e: '💙', k: ['blue', 'heart'] },
      { e: '💜', k: ['purple', 'heart'] },
      { e: '🖤', k: ['black', 'heart'] },
      { e: '💔', k: ['broken', 'heart'] },
      { e: '❣️', k: ['heart', 'exclamation'] },
      { e: '💕', k: ['two', 'hearts'] },
      { e: '💞', k: ['revolving', 'hearts'] },
      { e: '💓', k: ['beating', 'heart'] },
      { e: '💗', k: ['growing', 'heart'] },
      { e: '💖', k: ['sparkling', 'heart'] },
      { e: '💘', k: ['heart', 'with', 'arrow', 'cupid'] },
      { e: '💝', k: ['heart', 'with', 'ribbon', 'gift'] },
      { e: '💟', k: ['heart', 'decoration'] },
      { e: '💯', k: ['hundred', 'points', '100'] },
      { e: '💥', k: ['collision', 'boom', 'explode'] },
      { e: '💫', k: ['dizzy', 'stars'] },
      { e: '💦', k: ['sweat', 'droplets'] },
      { e: '💨', k: ['dashing', 'away', 'wind', 'smoke'] },
      { e: '✨', k: ['sparkles'] },
      { e: '🔥', k: ['fire', 'hot', 'lit'] },
      { e: '💤', k: ['zzz', 'sleeping'] },
    ],
  },
  {
    name: 'People & Body',
    emojis: [
      { e: '👋', k: ['waving', 'hand', 'hello', 'bye'] },
      { e: '🤚', k: ['raised', 'back', 'of', 'hand'] },
      { e: '🖐️', k: ['hand', 'with', 'fingers', 'splayed', 'high five'] },
      { e: '✋', k: ['raised', 'hand', 'stop'] },
      { e: '🖖', k: ['vulcan', 'salute', 'star trek'] },
      { e: '👌', k: ['ok', 'hand'] },
      { e: '🤏', k: ['pinching', 'hand', 'small'] },
      { e: '✌️', k: ['victory', 'hand', 'peace'] },
      { e: '🤞', k: ['crossed', 'fingers', 'luck'] },
      { e: '🤟', k: ['love-you', 'gesture'] },
      { e: '🤘', k: ['sign', 'of', 'the', 'horns', 'rock on'] },
      { e: '🤙', k: ['call', 'me', 'hand'] },
      { e: '👈', k: ['backhand', 'index', 'pointing', 'left'] },
      { e: '👉', k: ['backhand', 'index', 'pointing', 'right'] },
      { e: '👆', k: ['backhand', 'index', 'pointing', 'up'] },
      { e: '🖕', k: ['middle', 'finger'] },
      { e: '👇', k: ['backhand', 'index', 'pointing', 'down'] },
      { e: '☝️', k: ['index', 'pointing', 'up'] },
      { e: '👍', k: ['thumbs', 'up', 'like'] },
      { e: '👎', k: ['thumbs', 'down', 'dislike'] },
      { e: '✊', k: ['raised', 'fist'] },
      { e: '👊', k: ['oncoming', 'fist', 'punch'] },
      { e: '🤛', k: ['left-facing', 'fist'] },
      { e: '🤜', k: ['right-facing', 'fist'] },
      { e: '👏', k: ['clapping', 'hands', 'applause'] },
      { e: '🙌', k: ['raising', 'hands', 'praise', 'celebrate'] },
      { e: '👐', k: ['open', 'hands'] },
      { e: '🤲', k: ['palms', 'up', 'together'] },
      { e: '🤝', k: ['handshake'] },
      { e: '🙏', k: ['folded', 'hands', 'pray', 'please', 'thank you'] },
      { e: '💅', k: ['nail', 'polish', 'care', 'sass'] },
      { e: '🤳', k: ['selfie'] },
      { e: '💪', k: ['flexed', 'biceps', 'muscle', 'strong'] },
      { e: '🦾', k: ['mechanical', 'arm'] },
      { e: '🦿', k: ['mechanical', 'leg'] },
      { e: '🦵', k: ['leg'] },
      { e: '🦶', k: ['foot'] },
      { e: '👂', k: ['ear'] },
      { e: '👃', k: ['nose'] },
      { e: '🧠', k: ['brain'] },
      { e: '🦷', k: ['tooth'] },
      { e: '🦴', k: ['bone'] },
      { e: '👀', k: ['eyes', 'looking'] },
      { e: '👁️', k: ['eye'] },
      { e: '👅', k: ['tongue'] },
      { e: '👄', k: ['mouth'] },
      { e: '🧢', k: ['billed', 'cap', 'hat'] },
      { e: '👑', k: ['crown', 'king', 'queen'] },
      { e: '🫣', k: ['face', 'peeking', 'eyes', 'shy'] },
      { e: '😮‍💨', k: ['face', 'exhaling', 'sigh', 'relief'] },
    ],
  },
];
